[package]
name = "keep"
description = "Persistent terminal sessions"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "keep"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
crossterm = "0.29.0"
keep-ia = { version = "0.0.1", path = "../keep-ia" }
keep-proto = { version = "0.0.1", path = "../keep-proto" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
] }

[dev-dependencies]
keep-vt = { path = "../keep-vt" }
portable-pty = "0.9.0"
